<CFTRY>
	<CFIF session.langue EQ "fr">
		<cfset newLocal = SetLocale("French (Canadian)")>
	</CFIF>
	
	<CFSET VARIABLES.title_en = "DDR GIFTS REPORT">
	<CFSET file_name_en = "#APPLICATION.Racine#/en/secure/deposit-slip">
	<CFSET VARIABLES.title_fr = "DDR RAPPORT DONS">
	<CFSET file_name_fr = "#APPLICATION.Racine#/fr/secure/bordereau-depot">
	
	<cfinvoke component="#APPLICATION.cfcDonateurs#" method = "donateursListe" returnvariable ="tousDonateurs">
		<cfinvokeargument name="organismeID" value="#Session.utilisateur.organismeID#">
	</cfinvoke>
	<CFQUERY NAME="premier" dbtype="query">
		SELECT  Min(numero) as debut 
 		FROM tousDonateurs
	</CFQUERY>
	<CFQUERY NAME="dernier" dbtype="query">
		SELECT  Max(numero) as fin 
 		FROM tousDonateurs
	</CFQUERY>

	<CFParam name="date" default="toutes">
	<CFParam name="dateDebut" default="">
	<CFParam name="dateFin" default="">
	<CFParam name="donateurs" default="tous">
	<CFParam name="debut" default="#premier.debut#">
	<CFParam name="fin" default="#dernier.fin#">
	<CFParam name="typeexport" default="pdf">

	<CFIF isDefined('Form.rapport')>
		
		<cfinvoke component="#APPLICATION.cfcRapports#" method = "InfosOrganisme" returnvariable ="organisme">
			<cfinvokeargument name="organismeID" value="#Session.utilisateur.organismeID#">
		</cfinvoke>
		
		<cfinvoke component="#APPLICATION.cfcRapports#" method = "BordereauDepot" returnvariable ="bordereau">
			<cfinvokeargument name="organismeID" value="#Session.utilisateur.organismeID#">
			<cfinvokeargument name="date" value="#Form.date#">
			<cfinvokeargument name="dateDebut" value="#Form.dateDebut#">
			<cfinvokeargument name="dateFin" value="#Form.dateFin#">
			<cfinvokeargument name="donateurs" value="#Form.donateurs#">
			<cfinvokeargument name="debut" value="#Form.debut#">
			<cfinvokeargument name="fin" value="#Form.fin#">
			<cfinvokeargument name="langue" value="#session.langue#">
		</cfinvoke>		
		
		<!--- <cfset typerapport=Form.typerapport> --->
		
		<cfset date=Form.date>
		<cfset dateDebut=Form.dateDebut>
		<cfset dateFin=Form.dateFin>
		<cfset donateurs=Form.donateurs>
		<cfset debut=Form.debut>
		<cfset fin=Form.fin>
		
		<!--- <cfset typeexport=Form.typeexport> --->
		<CFIF session.langue EQ "fr">
			<cfset TitreRapport="BORDEREAU DE DéP&Ocirc;T - #organisme.organisme#">
			
		<CFELSE>
			<cfset TitreRapport="DEPOSIT SLIP - #organisme.organisme#">
		</CFIF>
		
		
		<cfdocument format="pdf"  overwrite="true" localURL="true">

			<cfdocumentitem type="header">
				<style>
					.BlocEntete{
						font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
						font-size: 14px;
						font-weight: normal;
						background-color: #DDDDDD;
						border-bottom:1px solid black;
						border-top:1px solid black;
					}
				</style>
				<table border=0 cellpadding=2 cellspacing=0 width="100%">
					<THEAD>
						<TH  CLASS="BlocEntete"><br><cfoutput>#TitreRapport#</cfoutput></TH>
					</THEAD>
				</table>
			</cfdocumentitem>
			<cfdocumentitem type="footer">
				<style>
					.BlocPiedDePage{
						font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
						font-size: 10px;
						font-weight: normal;
						background-color: #DDDDDD;
						border-bottom:1px solid black;
						border-top:1px solid black;
					}
				</style>
				<table border=0 cellpadding=2 cellspacing=0 width="100%" CLASS="BlocPiedDePage">
					<CFIF Session.langue EQ "fr">
						<tr>
							<td><em>Bordereau produit par DDR2 le <cfoutput>#LSDateFormat(Now(),"dd MMM yyyy")# &agrave #TimeFormat(now(),"HH:MM")#</cfoutput> </em></td>
							<td align="right">Page <cfoutput>#cfdocument.currentpagenumber# de #cfdocument.totalpagecount#</cfoutput></td>
						</tr>
					<CFELSE>
						<tr>
							<td><em>Deposit Slip generated by DDR2 on <cfoutput>#LSDateFormat(Now(),"yyyy MMM, dd")# at #TimeFormat(now(),"HH:MM")#</cfoutput> </em></td>
							<td align="right">Page <cfoutput>#cfdocument.currentpagenumber# of #cfdocument.totalpagecount#</cfoutput></td>
						</tr>
					</CFIF>
				</table>
			</cfdocumentitem>
			<cfdocumentsection>
				<style>
					.infoBordereau{
						font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
						font-size: 10px;
						font-weight: bold;
						padding:4px;
					}
					.EnteteColonne{
						font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
						font-size: 10px;
						font-weight: bold;
						border-bottom:1px solid black;
						border-top:1px solid black;
						background-color: #DDDDDD;
						padding:4px;
					}
					.BlocCorps{
						font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
						font-size: 11px;
						font-weight: normal;
					}
					.monnaie{
						font-family: monospace;
						font-size: 12px;
						font-weight: bold;
					}
				</style>
				<cfset totalMode=0>
				<cfset TotalDepot=0>
				<CFIF session.langue EQ "fr">
					
					<table WIDTH="100%" border="0" cellpadding=2 cellspacing=0 CLASS="BlocCorps">
						
						<tr class="infoBordereau">
							<td >Date du dép&ocirc;t : </td>
							<td >_______________</td>
							<td >Type d'opération :</td>
							<td >_______________</td>
						</tr>
						<tr class="infoBordereau">
							<td>No. de dép&ocirc;t : </td>
							<td>_______________</td>
							<td>Folio :</td>
							<td><CFIF organisme.folio NEQ ""><cfoutput>#organisme.folio#</cfoutput><CFELSE>_______________</CFIF></td>
						</tr>
						<tr class="infoBordereau">
							<td>Compte bancaire : </td>
							<td>_______________</td>
							<td>Transit :</td>
							<td><CFIF organisme.transit NEQ ""><cfoutput>#organisme.transit#</cfoutput><CFELSE>_______________</CFIF></td>
						</tr>
						<tr>
							<td colspan="4">&nbsp;</td>
						</tr>
						
						<tr>
							<td CLASS="EnteteColonne" style="width:20%;">Dossier</td>
							<td  CLASS="EnteteColonne" style="width:40%;">Nom</td>
							<td  CLASS="EnteteColonne" style="width:20%;">Mode de paiement</td>
							<td  CLASS="EnteteColonne" style="text-align:right;width:20%;">Montant</td>
						</tr>
						<cfoutput query="bordereau" GROUP="mode">
							<cfset nombreMode=0>
							<cfset totalMode=0>
							<cfset YourDate = CreateDate(#Year#, #month#, 1)>
							
							<tr>
								<td colspan="4">&nbsp;</td>
							</tr>
							
							<CFOUTPUT>
								<cfset totalMode=totalMode+montant>
								
								<tr>
									<td>#numero#</td>
									<td >#nom#, #prenom#</td>
									<td >#mode#</td>
									<td STYLE="text-align:right;">#LSCurrencyFormat(montant)#</td>
								</tr>
								<cfset nombreMode++>
							</CFOUTPUT>
							<cfset TotalDepot=TotalDepot+totalMode>
							
							<tr STYLE="line-height:20px;">
								<td colspan="2" STYLE="font-size:9px;font-weight:bold;">Nbre de dép&ocirc;ts #Lcase(mode)# : #nombreMode#</td>
								<td  STYLE="font-size:8pt;font-weight:bold;">Total (#mode#)</td>
								<td STYLE="text-align:right;border-bottom: solid 1px  black;font-weight:bold;">#LSCurrencyFormat(totalMode)#</td>
							</tr>
							
						</CFOUTPUT>
						
						<tr CLASS="BlocCorps" style="padding:4px 0px;">
							<td colspan="2" >&nbsp;</td>
							<td STYLE=" font-weight:bold; padding:4px 0px;">Total dép&ocirc;t</td>
							<td STYLE="text-align:right; font-weight:bold; font-size:11px;border-bottom: solid 2px  #BBB;padding:4px 0px;"><CFOUTPUT>#LSCurrencyFormat(TotalDepot)#</CFOUTPUT></td>
						</tr>
						
						<tr CLASS="BlocCorps" style="line-height:40px;">
							<td colspan="2" >&nbsp;</td>
							<td colspan="2" >Comptant :</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________   X&nbsp;&nbsp;&nbsp;5,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;&nbsp;10,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;&nbsp;20,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;&nbsp;50,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;100,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						
						<!--- <tr CLASS="monnaie" style="font-size:10px;">
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">_______ __________</td>
							<td >&nbsp;&nbsp;___________</td>
						</tr> --->
						<tr CLASS="monnaie" style="font-size:10px;">
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Monnaie &nbsp;</td>
							<td style="text-align:right;">= ______________</td>
						</tr>
						
						<!--- <tr >
							<td colspan="2" >&nbsp;</td>
							<td  STYLE="font-size:8pt;font-weight:bold;">Total comptant</td>
							<td STYLE="text-align:right;border-bottom: solid 2px  #BBB;font-weight:bold;"><cfoutput>#LSCurrencyFormat(totalMode)#</cfoutput></td>
						</tr> --->
						<tr>
							<td colspan="4">&nbsp;</td>
						</tr>
						<tr CLASS="BlocCorps" style="padding:4px 0px;">
							<td colspan="2" >_______________________________________</td>
							<td STYLE=" font-weight:bold; padding:4px 0px;">Total dép&ocirc;t</td>
							<td STYLE="text-align:right; font-weight:bold; font-size:11px;border-bottom: solid 2px  #BBB;padding:4px 0px;"><CFOUTPUT>#LSCurrencyFormat(TotalDepot)#</CFOUTPUT></td>
						</tr>
						<tr CLASS="BlocCorps" style="padding:4px 0px;">
							<td colspan="2" >Signature du déposant</td>
							<td colspan="2">&nbsp;</td>
							
						</tr>
					</table>
				<CFELSE>
					
					<table WIDTH="100%" border="0" cellpadding=2 cellspacing=0 CLASS="BlocCorps">
						
						<tr class="infoBordereau">
							<td >Date of deposit: </td>
							<td >_______________</td>
							<td >Type of operation:</td>
							<td >_______________</td>
						</tr>
						<tr class="infoBordereau">
							<td>Deposit No. : </td>
							<td>_______________</td>
							<td>Folio :</td>
							<td>_______________</td>
						</tr>
						<tr class="infoBordereau">
							<td>Bank Account : </td>
							<td>_______________</td>
							<td>Transit :</td>
							<td>_______________</td>
						</tr>
						<tr>
							<td colspan="4">&nbsp;</td>
						</tr>
						
						<tr>
							<td CLASS="EnteteColonne" style="width:20%;">Donor's No.</td>
							<td  CLASS="EnteteColonne" style="width:40%;">Name</td>
							<td  CLASS="EnteteColonne" style="width:20%;">Payment Method</td>
							<td  CLASS="EnteteColonne" style="text-align:right;width:20%;">Amount</td>
						</tr>
						<cfoutput query="bordereau" GROUP="mode">
							<cfset nombreMode=0>
							<cfset totalMode=0>
							<cfset YourDate = CreateDate(#Year#, #month#, 1)>
							
							<tr>
								<td colspan="4">&nbsp;</td>
							</tr>
							
							<CFOUTPUT>
								<cfset totalMode=totalMode+montant>
								
								<tr>
									<td>#numero#</td>
									<td >#nom#, #prenom#</td>
									<td >#mode#</td>
									<td STYLE="text-align:right;">#LSCurrencyFormat(montant)#</td>
								</tr>
								<cfset nombreMode++>
							</CFOUTPUT>
							<cfset TotalDepot=TotalDepot+totalMode>
							
							<tr STYLE="line-height:20px;">
								<td colspan="2" STYLE="font-size:9px;font-weight:bold;">Number of deposits #Lcase(mode)# : #nombreMode#</td>
								<td  STYLE="font-size:8pt;font-weight:bold;">Total (#mode#)</td>
								<td STYLE="text-align:right;border-bottom: solid 1px  black;font-weight:bold;">#LSCurrencyFormat(totalMode)#</td>
							</tr>
							
						</CFOUTPUT>
						
						<tr CLASS="BlocCorps" style="padding:4px 0px;">
							<td colspan="2" >&nbsp;</td>
							<td STYLE=" font-weight:bold; padding:4px 0px;">Total deposit</td>
							<td STYLE="text-align:right; font-weight:bold; font-size:11px;border-bottom: solid 2px  #BBB;padding:4px 0px;"><CFOUTPUT>#LSCurrencyFormat(TotalDepot)#</CFOUTPUT></td>
						</tr>
						
						<tr CLASS="BlocCorps" style="line-height:40px;">
							<td colspan="2" >&nbsp;</td>
							<td colspan="2" >Cash :</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________   X&nbsp;&nbsp;&nbsp;5,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;&nbsp;10,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;&nbsp;20,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;&nbsp;50,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						<tr CLASS="monnaie" >
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">________  X&nbsp;100,00 $</td>
							<td style="text-align:right;">= ____________</td>
						</tr>
						
						<!--- <tr CLASS="monnaie" style="font-size:10px;">
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">_______ __________</td>
							<td >&nbsp;&nbsp;___________</td>
						</tr> --->
						<tr CLASS="monnaie" style="font-size:10px;">
							<td colspan="2" >&nbsp;</td>
							<td style="text-align:right;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Currency &nbsp;</td>
							<td style="text-align:right;">= ______________</td>
						</tr>
						
						<!--- <tr >
							<td colspan="2" >&nbsp;</td>
							<td  STYLE="font-size:8pt;font-weight:bold;">Total Cash</td>
							<td STYLE="text-align:right;border-bottom: solid 2px  #BBB;font-weight:bold;"><cfoutput>#LSCurrencyFormat(totalMode)#</cfoutput></td>
						</tr> --->
						<tr>
							<td colspan="4">&nbsp;</td>
						</tr>
						<tr CLASS="BlocCorps" style="padding:4px 0px;">
							<td colspan="2" >_______________________________________</td>
							<td STYLE=" font-weight:bold; padding:4px 0px;">Total Deposit</td>
							<td STYLE="text-align:right; font-weight:bold; font-size:11px;border-bottom: solid 2px  #BBB;padding:4px 0px;"><CFOUTPUT>#LSCurrencyFormat(TotalDepot)#</CFOUTPUT></td>
						</tr>
						<tr CLASS="BlocCorps" style="padding:4px 0px;">
							<td colspan="2" >Signature</td>
							<td colspan="2">&nbsp;</td>
							
						</tr>
					</table>
					
				</CFIF>
			</cfdocumentsection>
			
		</cfdocument>
		
	</CFIF>
	
	<!DOCTYPE html>
	<!-- This site was created in Webflow. http://www.webflow.com-->
	<!-- Last Published: Thu Jun 16 2016 16:27:16 GMT+0000 (UTC) -->
	<html data-wf-site="5718896fb6f10eb45d8c7872" data-wf-page="5731981ac809f1bc5f09caa4">
		<head>
			<CFINCLUDE TEMPLATe="../_head.inc">
			<SCRIPT LANGUAGE="javascript">
			function CopieValeur(champ1,champ2)
				{
					document.getElementById(champ2).value = document.getElementById(champ1).value;
				}
			</SCRIPT>
			
			<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
			<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
			<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
			<CFIF session.langue EQ "en">
				<script>
					$( function() {
						$( "#dateDebut" ).datepicker({ dateFormat: 'yy-mm-dd' });
						$( "#dateFin" ).datepicker({ dateFormat: 'yy-mm-dd' });
					} );
				</script>
			<CFELSE>
				<script>
					$( function() {
						$("#dateDebut" ).datepicker({ 
						altField: "#datepicker",
						closeText: 'Fermer',
						prevText: 'Précédent',
						nextText: 'Suivant',
						currentText: 'Aujourd\'hui',
						monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
						monthNamesShort: ['Janv.', 'Févr.', 'Mars', 'Avril', 'Mai', 'Juin', 'Juil.', 'Août', 'Sept.', 'Oct.', 'Nov.', 'Déc.'],
						dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
						dayNamesShort: ['Dim.', 'Lun.', 'Mar.', 'Mer.', 'Jeu.', 'Ven.', 'Sam.'],
						dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
						weekHeader: 'Sem.',
						dateFormat: 'yy-mm-dd'
						});
						
						$( "#dateFin" ).datepicker({ 
						altField: "#datepicker",
						closeText: 'Fermer',
						prevText: 'Précédent',
						nextText: 'Suivant',
						currentText: 'Aujourd\'hui',
						monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
						monthNamesShort: ['Janv.', 'Févr.', 'Mars', 'Avril', 'Mai', 'Juin', 'Juil.', 'Août', 'Sept.', 'Oct.', 'Nov.', 'Déc.'],
						dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
						dayNamesShort: ['Dim.', 'Lun.', 'Mar.', 'Mer.', 'Jeu.', 'Ven.', 'Sam.'],
						dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
						weekHeader: 'Sem.',
						dateFormat: 'yy-mm-dd'
						});
					});
				</script>
				
			</CFIF>
		</head>

		<body> 
	
			<CFINCLUDE TEMPLATe="_menu.inc">
			
			<CFINCLUDE TEMPLATe="_organisme.inc">
	
			<!--- <div class="w-section sectionsousheader">
							<div class="w-container containersousheader">
				 				<div class="wrappersousheader">
				 					<CFIF session.langue EQ "fr">
										<h3 class="headingbreadcrumb"><a href="#APPLICATION.Racine#/fr/secure/accueil" style="color:#00b9ff;text-decoration:none;">Accueil</a> &gt; Rapports &gt; Rapport de dons</h3>
									<CFELSE>
										<h3 class="headingbreadcrumb"><a href="#APPLICATION.Racine#/en/secure/home" style="color:#00b9ff;text-decoration:none;">Home</a> &gt; Reports &gt; Gifts Report</h3>
									</CFIF>
				 				</div>
							</div>
						</div> --->
	
			<div class="w-section sectioncontenuprincipal">
			
				<CFINCLUDE TEMPLATe="_sous-menu-rapports.inc">
				
				<div class="w-container containerprincipal">
					<div class="blocfondblanc">
						<div class="containertyperapport">
							<div class="titretyperapport">
								<CFIF session.langue EQ "fr">
									<strong>BORDEREAU DE DéP&Ocirc;T</strong><BR>
									Pour les dons comptants et ch&egrave;ques (identifiés par le mode de paiement)
								<CFELSE>
									<strong>DEPOSIT SLIP</strong><BR>
									For cash donations and cheques (identified by payment method)
								</CFIF>
							</div>
        				</div>
        				
						<div class="w-form">
						
							<!--- LIEN VERS LES TUTORIELS --->
							<CFIF session.langue EQ "fr">
								<button style="background-color: white;" onClick="showHideTut()">
									<img width="100" src="<cfoutput>#APPLICATION.Racine#</cfoutput>/images/tutoriel.png">
								</button>
								<div id="videoTut" style="display: none;">
									<iframe width="90%" height="400" src="https://www.youtube.com/embed/hV57lDcwSF8?si=UNkZ9gLMmlOKIoeC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
								</div>
							<CFELSE>
								<button style="background-color: white;" onClick="showHideTut()">
									<img width="100" src="<cfoutput>#APPLICATION.Racine#</cfoutput>/images/tutorial.png">
								</button>
								<div id="videoTut" style="display: none;">
									<iframe width="90%" height="400" src="https://www.youtube.com/embed/4GFgmdr4qRY?si=P7lJ8pVapTmNW6i_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
								</div>
							</CFIF>
						
							<CFIF session.langue EQ "fr">
								<CFFORM data-name="Report Form" id="report-form" name="report-form" ACTION="#file_name_fr#" METHOD="POST">
									<div class="blocradiobuttons">
										<label class="labeldechamp" for="numdonateur">Date</label>
										<div class="selectionneurdate">
											<div class="w-radio champradiobutton radiobuttonpadding" data-ix="cacher-la-date">
												<cfinput class="w-radio-input" data-name="date" id="date" name="date" type="radio" value="toutes" checked="#date EQ 'toutes'#">
												<label class="w-form-label" for="datetoutes">Toutes</label>
											</div>
											<div class="w-radio champradiobutton radiobuttonpadding" data-ix="montrer-la-date">
												<cfinput class="w-radio-input" data-ix="montrer-la-date" data-name="date" id="date" name="date" type="radio" value="periode" checked="#date EQ 'periode'#">
												<label class="w-form-label" for="dateperiode">Sélectionner une période</label>
											</div>
										</div>
										<!--- <div class="selectionperiode" data-ix="display-none-on-load">
											<label class="labeldechamp" for="email">De :</label>
											<div class="w-embed champtexte">
												<CFinput type="datefield" value="#DateFormat(dateDebut, "yyyy-mm-dd")#" name="dateDebut" mask="yyyy-mm-dd" placeholder="aaaa-mm-jj"  style="margin:0;padding:0;"/>
											</div>
											<label class="labeldechamp" for="email">&Agrave; :</label>
											<div class="w-embed champtexte">
												<!--- <cfinput type="datefield" name="date" style="margin:0;padding:0;"> --->
												<CFinput type="datefield" value="#DateFormat(dateFin, "yyyy-mm-dd")#" name="dateFin" mask="yyyy-mm-dd" placeholder="aaaa-mm-jj"  style="margin:0;padding:0;"/>
											</div>
										</div> --->
										<div class="selectionperiode" data-ix="display-none-on-load">
											<label class="labeldechamp" for="email" style="margin:0px 10px;">De </label>
											<div class="w-embed champtexte">
												<input type="text" value="<cfoutput>#DateFormat(dateDebut, "yyyy-mm-dd")#</cfoutput>" name="dateDebut" id="dateDebut"  mask="yyyy-mm-dd" placeholder="aaaa-mm-jj"  pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" oninvalid="setCustomValidity('Veuillez entrer la date sous format aaaaa-mm-jj ')" onchange="try{setCustomValidity('')}catch(e){}" style="margin:0;margin-right:10px;width:140px;"/> 
											</div>
											<a href="##" ONCLICK="CopieValeur('dateDebut','dateFin')"><img  src="<cfoutput>#APPLICATION.Racine#</cfoutput>/images/flecheD.png"  TITLE="copier" style="height:25px;"></a>&nbsp;
											<label class="labeldechamp" for="email" style="margin:0px 10px;">&Agrave;</label>
											<div class="w-embed champtexte">
												<input type="text" value="<cfoutput>#DateFormat(dateFin, "yyyy-mm-dd")#</cfoutput>" name="dateFin" id="dateFin"  mask="yyyy-mm-dd" placeholder="aaaa-mm-jj"  pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" oninvalid="setCustomValidity('Veuillez entrer la date sous format aaaaa-mm-jj ')" onchange="try{setCustomValidity('')}catch(e){}" style="margin:0;padding:0;width:140px;"/> 
											</div>
										</div>
									</div>
									<div class="blocradiobuttons">
										<label class="labeldechamp" for="numdonateur">Donateurs</label>
										<div class="selectionneurdate">
											<div class="w-radio champradiobutton radiobuttonpadding" data-ix="cacher-la-selection-des-donateurs">
												<cfinput class="w-radio-input" data-ix="cacher-la-selection-des-donateurs" data-name="donateurs" id="donateurs" name="donateurs" type="radio" value="tous" checked="#donateurs EQ 'tous'#">
												<label class="w-form-label" for="donateurstous">Tous</label>
											</div>
											<div class="w-radio champradiobutton radiobuttonpadding" data-ix="montrer-la-selection-de-donateurs">
												<cfinput class="w-radio-input" data-ix="montrer-la-selection-de-donateurs" data-name="donateurs" id="donateurs" name="donateurs" type="radio" value="selection" checked="#donateurs EQ 'selection'#">
												<label class="w-form-label" for="donateursselection">Sélectionner les donateurs</label>
											</div>
										</div>
										<div class="selectionnumdonateurs" data-ix="display-none-on-load-2">
											<label class="labeldechamp" for="Debut">De :</label>
											<input class="w-input champnumdonateur" data-name="Debut #" id="Debut" maxlength="256" name="Debut" placeholder="# donateur" required="required" type="text" value="<cfoutput>#debut#</cfoutput>">
											<label class="labeldechamp" for="Fin">&Agrave; :</label>
											<input class="w-input champnumdonateur" data-name="Fin #" id="Fin" maxlength="256" name="Fin" placeholder="# donateur" required="required" type="text" value="<cfoutput>#fin#</cfoutput>">
										</div> 
										
									</div>

									<div class="blocchamp blocchamppleinelargeur">
									<cfinput class="w-button boutonvalider" data-wait="Préparation du rapport en cours" name="rapport" type="submit" formtarget="_blank" value="Générer le rapport" wait="Préparation du rapport en cours">
									</div>
								</CFFORM>
							<CFELSE>
								<CFFORM data-name="Report Form" id="report-form" name="report-form" ACTION="#file_name_en#" METHOD="POST">
									
									
									
									<div class="blocradiobuttons">
										<label class="labeldechamp" for="numdonateur">Date</label>
										<div class="selectionneurdate">
											<div class="w-radio champradiobutton radiobuttonpadding" data-ix="cacher-la-date">
												<cfinput class="w-radio-input" data-name="date" id="date" name="date" type="radio" value="toutes" checked="#date EQ 'toutes'#">
												<label class="w-form-label" for="datetoutes">All</label>
											</div>
											<div class="w-radio champradiobutton radiobuttonpadding" data-ix="montrer-la-date">
												<cfinput class="w-radio-input" data-ix="montrer-la-date" data-name="date" id="date" name="date" type="radio" value="periode" checked="#date EQ 'periode'#">
												<label class="w-form-label" for="dateperiode">Select period</label>
											</div>
										</div>
										<!--- <div class="selectionperiode" data-ix="display-none-on-load">
											<label class="labeldechamp" for="email">From :</label>
											<div class="w-embed champtexte">
												<CFinput type="datefield" value="#DateFormat(dateDebut, "yyyy-mm-dd")#" name="dateDebut" mask="yyyy-mm-dd" placeholder="yyyy-mm-dd"  style="margin:0;padding:0;"/>
											</div>
											<label class="labeldechamp" for="email">To :</label>
											<div class="w-embed champtexte">
												<!--- <cfinput type="datefield" name="date" style="margin:0;padding:0;"> --->
												<CFinput type="datefield" value="#DateFormat(dateFin, "yyyy-mm-dd")#" name="dateFin" mask="yyyy-mm-dd" placeholder="yyyy-mm-dd"  style="margin:0;padding:0;"/>
											</div>
										</div> --->
										<div class="selectionperiode" data-ix="display-none-on-load">
											<label class="labeldechamp" for="email" style="margin:0px 10px;">From </label>
											<div class="w-embed champtexte">
												<input type="text" value="<cfoutput>#DateFormat(dateDebut, "yyyy-mm-dd")#</cfoutput>" name="dateDebut" id="dateDebut"  mask="yyyy-mm-dd" placeholder="aaaa-mm-jj"  pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" oninvalid="setCustomValidity('Date should have aaaaa-mm-jj format')" onchange="try{setCustomValidity('')}catch(e){}" style="margin:0;margin-right:10px;width:140px;"/> 
											</div>
											<a href="##" ONCLICK="CopieValeur('dateDebut','dateFin')"><img  src="<cfoutput>#APPLICATION.Racine#</cfoutput>/images/flecheD.png"  TITLE="Copy" style="height:25px;"></a>
											<label class="labeldechamp" for="email" style="margin:0px 10px;">To </label>
											<div class="w-embed champtexte">
												<input type="text" value="<cfoutput>#DateFormat(dateFin, "yyyy-mm-dd")#</cfoutput>" name="dateFin" id="dateFin"  mask="yyyy-mm-dd" placeholder="aaaa-mm-jj"  pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" oninvalid="setCustomValidity('Date should have aaaaa-mm-jj format')" onchange="try{setCustomValidity('')}catch(e){}" style="margin:0;padding:0;width:140px;"/> 
											</div>
										</div>
									</div>
									<div class="blocradiobuttons">
									<label class="labeldechamp" for="numdonateur">Donors</label>
									<div class="selectionneurdate">
										<div class="w-radio champradiobutton radiobuttonpadding" data-ix="cacher-la-selection-des-donateurs">
											<cfinput class="w-radio-input" data-ix="cacher-la-selection-des-donateurs" data-name="donateurs" id="donateurs" name="donateurs" type="radio" value="tous" checked="#donateurs EQ 'tous'#">
											<label class="w-form-label" for="donateurstous">All</label>
										</div>
										<div class="w-radio champradiobutton radiobuttonpadding" data-ix="montrer-la-selection-de-donateurs">
											<cfinput class="w-radio-input" data-ix="montrer-la-selection-de-donateurs" data-name="donateurs" id="donateurs" name="donateurs" type="radio" value="selection" checked="#donateurs EQ 'selection'#">
											<label class="w-form-label" for="donateursselection">Select donors</label>
										</div>
									</div>
									<div class="selectionnumdonateurs" data-ix="display-none-on-load-2">
										<label class="labeldechamp" for="Debut">From :</label>
										<input class="w-input champnumdonateur" data-name="Debut #" id="Debut" maxlength="256" name="Debut" placeholder="# donateur" required="required" type="text" value="<cfoutput>#debut#</cfoutput>">
										<label class="labeldechamp" for="Fin">To :</label>
										<input class="w-input champnumdonateur" data-name="Fin #" id="Fin" maxlength="256" name="Fin" placeholder="# donateur" required="required" type="text" value="<cfoutput>#fin#</cfoutput>">
									</div>
									</div>
									
									<!--- <div class="blocradiobuttons">
										<div class="containerradiobuttons">
											<div class="w-radio w-clearfix champradiobutton">
												<CFinput class="w-radio-input" data-name="typeexport" id="typeexport" name="typeexport" type="radio" value="pdf" checked="#typeexport EQ 'pdf'#">
												<label class="w-form-label petittextegris" for="pdf">Export PDF</label>
											</div>
											<div class="w-radio w-clearfix champradiobutton">
												<CFinput class="w-radio-input" data-name="typeexport" id="typeexport" name="typeexport" type="radio" value="excel" checked="#typeexport EQ 'excel'#">
												<label class="w-form-label petittextegris" for="excel">Export Excel</label>
											</div>
										</div>
									</div> --->
									<div class="blocchamp blocchamppleinelargeur">
									<cfinput class="w-button boutonvalider" data-wait="Report is being processed" name="rapport" type="submit" formtarget="_blank" value="Display report" wait="Report is being processed">
									</div>
								</CFFORM>
							</CFIF>
						</div>
      			</div>
    			</div>
			</div><!--- <div class="w-section sectioncontenuprincipal"> --->
			<CFINCLUDE TEMPLATe="../_footer.inc">
		
			<!--- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> --->
			<script type="text/javascript" src="<cfoutput>#APPLICATION.Racine#</cfoutput>/js/webflow.js"></script>
			<!--[if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
 		</body>
 	</html>
	
	<script type='text/javascript'>
		function showHideTut() {
        var x = document.getElementById("videoTut");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
            y.style.display = "block";
        }
    }
	</script>
	
	<CFCATCH>
		
		<!--- <CFINCLUDE TEMPLATE="../_envoi_erreur.inc"> 
				<CFIF Session.langue EQ "fr">
					<CFLOCATION URL="#APPLICATION.Racine#/fr/erreur" ADDTOKEN="NO">
				<CFELSE>
					<CFLOCATION URL="#APPLICATION.Racine#/en/error" ADDTOKEN="NO">
				</CFIF> --->
	
	<cfoutput>
				#DateFormat(now(),"DD MMMM, YYYY")# #TimeFormat(now(),"(HH:MM:SS)")#<br>
				Une erreur est survenue sur DDR
				<BR>
				<CFIF isDefined('Session.utilisateur.prenom')>
				Utilisateur : #Session.utilisateur.prenom# #Session.utilisateur.nom# <BR>
				</CFIF>
				<cfif IsDefined('cfcatch')> Message : #cfcatch.Message#<BR></CFIF>
								
				<cfif IsDefined('cfcatch')><cfdump var="#cfcatch#" label="cfcatch"></cfif>
				<HR>
				<cfdump var="#Form#" label="Form Variables">
				<HR>
				<cfdump var="#URL#" label="URL Variables">
				<HR>
				<cfdump var="#session#" label="Session Variables">
			</cfoutput>
	</CFCATCH>
</CFTRY>